version: "3.4"

services:
  catalogdb:
    image: mongo
    
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile-
  basket.apı:
    image: basket.apı
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
