services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
    
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    
  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
      
  portainer:
    image: portainer/portainer-ce
      
volumes:
  mongo_data:
  portainer_data: