services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine
    
  discountdb:
    image: postgres
    
  pgadmin:
    image: dpage/pgadmin4
    
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    
  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    
  discount.api:
    image: discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
      
  portainer:
    image: portainer/portainer-ce
      
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: